project:
  type: website
  output-dir: docs
  
website:
  title: "Applied Biostatistics Course with R"
  navbar: 
    left:
      - text: "Home"
        href: index.qmd
      - text: "Install materials"
        href: how_to.qmd
      - text: "Slides"
        href: slides.qmd
      
format: 
  html:
    theme: minty
    toc: true
  



