project:
  type: website
  output-dir: docs
  
website:
  title: "Curs de REDCap"
  navbar: 
    left:
      - text: "Inici"
        href: index.qmd
      - text: "Diapositives"
        href: slides.qmd
      - text: "Autors"
        href: authors.qmd
      
format: 
  html:
    theme: 
      - minty
      - WWW/custom.scss
    toc: true
  



