project:
  type: website
  output-dir: docs
  
website:
  title: "curs_bioestadistica_R"
  navbar: 
    left:
      - index.qmd
      - how_to.qmd
      - materials.qmd
      
format: 
  html:
    theme: minty
    toc: true
  



